name: tfg_v2
description: Second version of TFG. Now with architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  age_calculator: ^1.0.0
  dio: ^5.3.0
  easy_localization: ^3.0.2
  either_dart: ^1.0.0
  expandable_text: ^2.3.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^9.0.0
  injectable: ^2.1.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

  build_runner: ^2.4.5
  injectable_generator: ^2.1.6

  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Futura-Light
      fonts:
        - asset: assets/fonts/Futura-Light.ttf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura-Medium.ttf
    - family: Futura-Bold
      fonts:
        - asset: assets/fonts/Futura-Bold.ttf
    - family: Futura-ExtraBold
      fonts:
        - asset: assets/fonts/Futura-ExtraBold.otf